# nixpacks.toml (Ã  la racine)

[phases.build]
cmds = [
  "composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader",

  "php bin/console cache:clear --env=prod",
  "php bin/console cache:warmup --env=prod",

  "php bin/console assets:install public --env=prod",

  "php bin/console doctrine:database:create --if-not-exists --env=prod || true",
  "php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration --env=prod || true"
]

[start]
cmd = "php -S 0.0.0.0:${PORT} -t public"
