[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "php bin/console cache:clear --env=prod",
  "php bin/console cache:warmup --env=prod",
  "php bin/console doctrine:migrations:migrate --no-interaction --env=prod"
]

[start]
cmd = "php -S 0.0.0.0:${PORT} -t public"
